theme: jekyll-theme-minimal

# theme configurations
title: ไฟล์ในโครงการรับนักเรียนเข้าฝึกทักษะวิจัย ณ สวทช.
description: ไฟล์ทั้งหมดที่ใช้และสร้างที่เกี่ยวข้องขณะเข้าร่วมการฝึกทักษะวิจัยที่ NECTEC สวทช.
lang: th-TH
github:
  is_user_page: true